package Controllers;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import Models.Message_Box;
import javafx.application.Platform;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.scene.input.KeyEvent;

public class LoginController {
	@FXML
	private TextField TextField_UserName;
	@FXML
	private Button Button_Subtmit, Button_Close;
	@FXML
	private Label Label_Sign_In;
	@FXML
	private PasswordField PassWordField_Password;
	
	
	public Message_Box Msg_Box = new Message_Box();
	public Stage primaryStage;

	
	// Event Listener on TextField[#TextField_UserName].onKeyPressed
	@FXML
	public void OnKeyPressUsser(KeyEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#Button_Subtmit].onAction
	@FXML
	public void OnClickSubmit(ActionEvent event) {
		try {
			Scene scene = new Scene((Parent) FXMLLoader.load(getClass().getResource("/View/Sign_In.fxml")));
			
			primaryStage = new Stage();
			

			scene.setFill(Color.TRANSPARENT);

			primaryStage.setTitle("Sign In");
			primaryStage.initStyle(StageStyle.TRANSPARENT);
			
			
			primaryStage.setScene(scene);
			
			primaryStage.show();
		} catch(Exception e) {
			Msg_Box.message_box(e, "Login Controller");
		}
	}
	
	// Event Listener on Label[#Label_Sign_In].onMouseClicked
	@FXML
	public void OnMouseClickedSignIn(MouseEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on PasswordField[#PassWordField_Password].onKeyPressed
	@FXML
	public void OnKeyPressPassWord(KeyEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#Button_Close].onAction
	@FXML
	public void OnClickClose(ActionEvent event) {
		// TODO Autogenerated
		Platform.exit();
	}
}
