package Controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import Models.Message_Box;
import javafx.application.Platform;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

import javafx.scene.input.MouseEvent;

import javafx.scene.input.KeyEvent;

public class Sign_InController {
	@FXML
	private TextField TextField_First, TextField_User, TextField_Laste;
	@FXML
	private PasswordField TextField_PassWord;
	@FXML
	private Label Label_Login;
	@FXML
	private Button Button_Subtmit, Button_Close;
	
	public Message_Box Msg_Box = new Message_Box();

	
	// Event Listener on TextField[#TextField_First].onKeyPressed
	@FXML
	public void OnKeyPressedFirst(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#TextField_Laste].onKeyPressed
	@FXML
	public void OnKeyPressedLast(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#TextField_User].onKeyPressed
	@FXML
	public void OnKeyPressedUser(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on PasswordField[#TextField_PassWord].onKeyPressed
	@FXML
	public void OnKeyPressedPass(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Label[#Label_Login].onMouseClicked
	@FXML
	public void OnClickLogin(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Button_Subtmit].onAction
	@FXML
	public void OnClickSignIn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Button_Close].onAction
	@FXML
	public void OnClickClose(ActionEvent event) {
		// TODO Autogenerated
		
	}
}
