package Controllers;

import javafx.fxml.*;
import javafx.scene.control.*;

import DAO_Brief.*;
import Models.*;
import javafx.application.Platform;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.input.KeyEvent;

public class LoginController {
    @FXML
    private TextField TextField_UserName;
    @FXML
    private Button Button_Subtmit, Button_Close;
    @FXML
    private Label Label_Sign_In;
    @FXML
    private PasswordField PassWordField_Password;
    @FXML
    private AnchorPane PaneID;

    private Users user = new Users();
    private DAO_Users DAO_user = new DAO_Users();
    private Message_Box Msg_Box = new Message_Box();
    private Form Ope_Form = new Form();


    // Event Listener on TextField[#TextField_UserName].onKeyPressed
    @FXML
    public void OnKeyPressUsser(KeyEvent event) {
        // TODO Autogenerated
        TextField_UserName.setStyle("-fx-background-color: White;");
    }

    // Event Listener on Button[#Button_Subtmit].onAction
    @FXML
    public void OnClickSubmit(ActionEvent event) {
        try {
            DAO_user.test_Connection(user ,TextField_UserName.getText() ,PassWordField_Password.getText());

            TextField_UserName.setText("");
            PassWordField_Password.setText("");

            if(user.getUser_Name() != null) Ope_Form.Open_Form("Home");
            else {
                TextField_UserName.setStyle("-fx-background-color: red;");
                PassWordField_Password.setStyle("-fx-background-color: red;");
            }

        } catch (Exception e) {
            // TODO: handle exception
            Msg_Box.message_box(e, "Login Contriller Submit");
        }
    }

    // Event Listener on Label[#Label_Sign_In].onMouseClicked
    @FXML
    public void OnMouseClickedSignIn(MouseEvent event) {
        // TODO Autogenerated
        Ope_Form.Open_Form("Sign_In");
    }

    // Event Listener on PasswordField[#PassWordField_Password].onKeyPressed
    @FXML
    public void OnKeyPressPassWord(KeyEvent event) {
        // TODO Autogenerated
        PassWordField_Password.setStyle("-fx-background-color: White;");
    }

    // Event Listener on Button[#Button_Close].onAction
    @FXML
    public void OnClickClose(ActionEvent event) {
        // TODO Autogenerated
        Platform.exit();
    }
}
