package Controllers;

import javafx.fxml.FXML;
import javafx.scene.control.*;
import DAO_Brief.DAO_Users;
import Models.*;
import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import javafx.scene.input.KeyEvent;

public class Sign_InController {
    @FXML
    private TextField TextField_First, TextField_User, TextField_Laste;
    @FXML
    private PasswordField TextField_PassWord;
    @FXML
    private Label Label_Login;
    @FXML
    private Button Button_Subtmit, Button_Close;

    public Message_Box Msg_Box = new Message_Box();
    public Stage primaryStage;
    public Users user = new Users();
    public DAO_Users DAO_user = new DAO_Users();


    // Event Listener on TextField[#TextField_First].onKeyPressed
    @FXML
    public void OnKeyPressedFirst(KeyEvent event) {
        // TODO Autogenerated
        TextField_First.setStyle("-fx-background-color: White;");
    }
    // Event Listener on TextField[#TextField_Laste].onKeyPressed
    @FXML
    public void OnKeyPressedLast(KeyEvent event) {
        // TODO Autogenerated
        TextField_Laste.setStyle("-fx-background-color: White;");
    }
    // Event Listener on TextField[#TextField_User].onKeyPressed
    @FXML
    public void OnKeyPressedUser(KeyEvent event) {
        // TODO Autogenerated
        TextField_User.setStyle("-fx-background-color: White;");
    }
    // Event Listener on PasswordField[#TextField_PassWord].onKeyPressed
    @FXML
    public void OnKeyPressedPass(KeyEvent event) {
        // TODO Autogenerated
        TextField_PassWord.setStyle("-fx-background-color: White;");
    }
    // Event Listener on Label[#Label_Login].onMouseClicked

    @FXML
    public void OnClickLogin(MouseEvent event) {
        // TODO Autogenerated
        primaryStage = (Stage) Button_Close.getScene().getWindow();

        primaryStage.close();
    }
    // Event Listener on Button[#Button_Subtmit].onAction
    @FXML
    public void OnClickSignIn(ActionEvent event) {
        if (TextField_First.getText() == "" || TextField_User.getText() == ""
                || TextField_Laste.getText() == "" || TextField_PassWord.getText() == "") {
            if(TextField_First.getText() == "")TextField_First.setStyle("-fx-background-color: Red;");
            if(TextField_User.getText() == "")TextField_User.setStyle("-fx-background-color: Red;");
            if(TextField_Laste.getText() == "")TextField_Laste.setStyle("-fx-background-color: Red;");
            if(TextField_PassWord.getText() == "")TextField_PassWord.setStyle("-fx-background-color: Red;");
        }else {
            try {
                DAO_user.lister(user);
                user.setFirst_Name(TextField_First.getText());
                user.setLast_Name(TextField_Laste.getText());
                user.setUser_Name(TextField_User.getText());
                user.setUser_PassWord(TextField_PassWord.getText());
                DAO_user.Ajouter(user);
                OnClickClose(event);
            } catch (Exception e) {
                Msg_Box.message_box(e, "Sign in Controller");
            }
        }

    }
    // Event Listener on Button[#Button_Close].onAction
    @FXML
    public void OnClickClose(ActionEvent event) {
        // TODO Autogenerated
        primaryStage = (Stage) Button_Close.getScene().getWindow();

        primaryStage.close();

    }
}
