package Controllers;

import DAO_Brief.DAO_Category;
import javafx.collections.transformation.FilteredList;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.*;

import java.net.URL;
import java.util.ResourceBundle;

import DAO_Brief.DAO_Task;
import Models.*;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.TextArea;

import javafx.scene.input.KeyEvent;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import javafx.scene.control.DatePicker;

public class TaskController implements Initializable {

    ObservableList<String> option = FXCollections.observableArrayList("pas encore","en cours","terminée");

    public ObservableList<Category> getCandidatList(){

        ObservableList<Category> CategoryList = FXCollections.observableArrayList();

        try{
            DAO_category.Remp_Combobox(category, CategoryList);
        }catch(Exception e){
            Msg_Box.message_box(e,"Obervablelist Controller task");;
        }
        return CategoryList;
    }


    @FXML
    private Button ID_Button_Close, ID_Button_Add, ID_Button_Delete, ID_Button_Update;
    @FXML
    private TextField ID_TextField_Title, ID_TextField_ID;
    @FXML
    private ComboBox<String> ID_Combobox_Status = new ComboBox(option);
    @FXML
    private ComboBox<Category> ID_Combobox_Category/*  = new ComboBox(option)*/;
    @FXML
    private DatePicker ID_DatePicker;
    @FXML
    private TextArea ID_TextArea_Desc;
    @FXML
    private Label Label_Category;

    private Stage primaryStage;
    private Task task;
    private Category category;
    private DAO_Task DAO_task = new DAO_Task();

    private DAO_Category DAO_category = new DAO_Category();
    private Message_Box Msg_Box = new Message_Box();
    private Form open_Form = new Form();

    public void AfficheCandidats(){
        ID_Combobox_Category.getItems().clear();

		ObservableList<Category> list = getCandidatList();
        //FilteredList<Category> selectFiltered = new FilteredList<>(list, i-> Boolean.parseBoolean(i.getName()));

		ID_Combobox_Category.setItems(list);
    }

    public void Clean() {
        ID_TextField_Title.setText("");
        ID_TextField_ID.setText("");
        ID_TextArea_Desc.setText("");
        ID_Combobox_Category.setValue(null);
        ID_Combobox_Status.setValue(null);
        ID_DatePicker.setValue(null);
    }

    @FXML
    public void OnClickClose(ActionEvent event) {
        // TODO Autogenerated

        primaryStage = (Stage) ID_Button_Close.getScene().getWindow();

        primaryStage.close();
    }
    @FXML
    public void OnClickAdd(ActionEvent event) {
        if (ID_TextField_Title.getText() == "" || ID_TextArea_Desc.getText() == "" || ID_DatePicker.getValue() == null
        || ID_Combobox_Status.getValue() == null ) {
            if(ID_TextField_Title.getText() == "")ID_TextField_Title.setStyle("-fx-background-color: Red;");
            if(ID_Combobox_Status.getValue() == null)ID_Combobox_Status.setStyle("-fx-background-color: Red;");
            if(ID_TextArea_Desc.getText() == "")ID_TextArea_Desc.setStyle("-fx-background-color: Red;");
            if(ID_DatePicker.getValue() == null)ID_DatePicker.setStyle("-fx-background-color: Red;");
        }else {
            try {
                task = new Task();

                DAO_task.lister(task);

                task.setTitle(ID_TextField_Title.getText());
                task.setDescription(ID_TextArea_Desc.getText());
                task.setStatus(ID_Combobox_Status.getValue());
                task.setDeadline(ID_DatePicker.getValue());
                task.setID_Category(1);

                DAO_task.Ajouter(task);

                Clean();
                //AfficheCandidats();
            }catch(Exception e) {
                Msg_Box.message_box(e,"Ajouter Controller");
            }
        }
    }
    @FXML
    public void OnClickDelete(ActionEvent event) {
        if (ID_TextField_ID.isVisible()){
            if (ID_TextField_ID.getText() != "") {
                try {

                    task = new Task();

                    task.setID_task(Integer.parseInt(ID_TextField_ID.getText()));


                    DAO_task.supprimer(task);

                    ID_TextField_ID.setStyle("visibility : false");

                    Clean();

                }catch(Exception e) {
                    Msg_Box.message_box(e,"Supprimer Controller");
                }
            }else {
                ID_TextField_ID.setStyle("-fx-background-color: Red;");
            }
        }else {
            ID_TextField_ID.setStyle("visibility : true");
        }

    }
    @FXML
    public void OnClickUpdate(ActionEvent event) {
        if (ID_TextField_ID.isVisible()){
            if (ID_TextField_ID.getText() != "") {
                if (ID_TextField_Title.getText() == "" || ID_TextArea_Desc.getText() == "" || ID_DatePicker.getValue() == null
                        || ID_Combobox_Status.getValue() == null ) {
                    if(ID_TextField_Title.getText() == "")ID_TextField_Title.setStyle("-fx-background-color: Red;");
                    if(ID_Combobox_Status.getValue() == null)ID_Combobox_Status.setStyle("-fx-background-color: Red;");
                    if(ID_TextArea_Desc.getText() == "")ID_TextArea_Desc.setStyle("-fx-background-color: Red;");
                    if(ID_DatePicker.getValue() == null)ID_DatePicker.setStyle("-fx-background-color: Red;");
                }else {
                    try {
                        task = new Task();

                        task.setID_task(Integer.parseInt(ID_TextField_ID.getText()));
                        task.setTitle(ID_TextField_Title.getText());
                        task.setDescription(ID_TextArea_Desc.getText());
                        task.setStatus(ID_Combobox_Status.getValue());
                        task.setDeadline(ID_DatePicker.getValue());
                        task.setID_Category(2);

                        DAO_task.modifier(task);

                        ID_TextField_ID.setStyle("visibility : false");

                        Clean();
                    }catch(Exception e) {
                        Msg_Box.message_box(e,"Modifier Controller");
                    }
                }
            }else {
                ID_TextField_ID.setStyle("-fx-background-color: Red;");
            }
        }else {
            ID_TextField_ID.setStyle("visibility : true");
        }




    }
    @FXML
    public void OnKeyPressed_Title(KeyEvent event) {
        // TODO Autogenerated
        ID_TextField_Title.setStyle("-fx-background-color: White;");
    }
    @FXML
    public void OnKeyPressed_Id(KeyEvent event) {
        // TODO Autogenerated
        ID_TextField_ID.setStyle("-fx-background-color: White;");

    }
    @FXML
    public void OnClick_Category(ActionEvent event) {
        // TODO Autogenerated
        ID_Combobox_Category.setStyle("-fx-background-color: White;");
    }
    @FXML
    public void OnClick_DeadLine(ActionEvent event) {
        // TODO Autogenerated
        ID_DatePicker.setStyle("-fx-background-color: White;");
    }
    @FXML
    public void OnClick_Status(ActionEvent event) {
        // TODO Autogenerated
        ID_Combobox_Status.setStyle("-fx-background-color: White;");
    }
    @FXML
    public void OnKeyPressed_Description(KeyEvent event) {
        // TODO Autogenerated
        ID_TextArea_Desc.setStyle("-fx-background-color: White;");
    }
    @FXML
    public void OnMouseClickedAdd(MouseEvent event) {
        open_Form.Open_Form("Category");
    }

    public void initialize(URL arg0, ResourceBundle arg1) {
        ID_Combobox_Status.setItems(option);
        AfficheCandidats();
    }
}
