package application;

import javafx.fxml.*;
import javafx.scene.control.*;
import javafx.scene.control.cell.PropertyValueFactory;

import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ResourceBundle;

import Classes.*;
import DAO_Pa.*;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

public class FormController implements Initializable {
	
	public Message_Box Msg_Box = new Message_Box();
	
	public DAO_Candidat DAO_Cand = new DAO_Candidat();;
	public Candidat Cand;
	public Connect con = new Connect();
	
	@FXML
	private TextField textField_Id, textField_Nom, textField_Prenom, textField_MAil, textField_Adresse, textField_Ville, textField_Pays;
	@FXML
	private TableColumn<Candidat, String> Candid_Id, Candid_Nom, Candid_Pre, Candid_Mail, Candid_Adr, Candid_Ville, Candid_Pays;
	@FXML
	private TableView<Candidat> TableView_Aff; 

	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
			try {
				AfficheCandidats();
			} catch (Exception e) {
				// TODO: handle exception
				Msg_Box.message_box(e,"Initialize Controller");
			}
		
	}
	
	public ObservableList<Candidat> getCandidatList(){
		
        ObservableList<Candidat> candidatList = FXCollections.observableArrayList();


        ResultSet rs;
        try{
            rs = con.Connexion().createStatement().executeQuery("select * from Info");
            Candidat candidat;
            while(rs.next()){
            	candidat =new Candidat(rs.getString("identifiant"),rs.getString("nom"),rs.getString("prenom"),rs.getString("mail"),
            			rs.getString("adresse"),rs.getString("ville"),rs.getString("pays"));
            	candidatList.add(candidat);
            }

        }catch(Exception e){
            Msg_Box.message_box(e,"Obervablelist Controller");;
        }
        return candidatList;
    }
	
	public void AfficheCandidats(){
		TableView_Aff.getItems().clear();
		ObservableList<Candidat> list =getCandidatList();
		Candid_Id.setCellValueFactory(new PropertyValueFactory<Candidat,String>("identifiant"));
		Candid_Nom.setCellValueFactory(new PropertyValueFactory<Candidat,String>("nom"));
		Candid_Pre.setCellValueFactory(new PropertyValueFactory<Candidat,String>("prenom"));
		Candid_Mail.setCellValueFactory(new PropertyValueFactory<Candidat,String>("mail"));
		Candid_Adr.setCellValueFactory(new PropertyValueFactory<Candidat,String>("adresse"));
		Candid_Ville.setCellValueFactory(new PropertyValueFactory<Candidat,String>("ville"));
		Candid_Pays.setCellValueFactory(new PropertyValueFactory<Candidat,String>("pays"));
		TableView_Aff.setItems(list);
	}
	
	
	public void Clean() {
		textField_Id.setText("");
		textField_Nom.setText("");
		textField_Prenom.setText("");
		textField_MAil.setText("");
		textField_Adresse.setText("");
		textField_Ville.setText("");
		textField_Pays.setText("");
	}
	
	
	@FXML
	public void OnClickAjouter(ActionEvent event) {
		// TODO Autogenerated
		try {
			Cand = new Candidat(textField_Id.getText(), textField_Nom.getText(), textField_Prenom.getText(), textField_MAil.getText(), textField_Adresse.getText()
					, textField_Ville.getText(), textField_Pays.getText());

			DAO_Cand.Create(Cand);
			
			con.Connexion().close();
			
			Clean();
			AfficheCandidats();
		}catch(Exception e) {
			Msg_Box.message_box(e,"Ajouter Controller");
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void OnClickModifier(ActionEvent event) {
		// TODO Autogenerated
		try {
			
			Cand = new Candidat(textField_Id.getText());
			
			Cand.setNom(textField_Nom.getText());
			Cand.setPrenom(textField_Prenom.getText());
			Cand.setMail(textField_MAil.getText());
			Cand.setAdresse(textField_Adresse.getText());
			Cand.setVille(textField_Ville.getText());
			Cand.setPays(textField_Pays.getText());
			
			DAO_Cand.Update(Cand);
			
			con.Connexion().close();

			Clean();

			AfficheCandidats();
		}catch(Exception e) {
			Msg_Box.message_box(e,"Modifier Controller");
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void OnClickSupprimer(ActionEvent event) {
		// TODO Autogenerated
		try {

			//TableView_Aff.getItems().remove(TableView_Aff.getSelectionModel().getSelectedItem());
			
			Cand = new Candidat(textField_Id.getText());
			
			DAO_Cand.Delete(Cand);
			
			
			con.Connexion().close();
			
			Clean();

			AfficheCandidats();
		}catch(Exception e) {
			Msg_Box.message_box(e,"Supprimer Controller");
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void OnClickAfficher(ActionEvent event) {
		// TODO Autogenerated
		try {
			Cand = new Candidat();
			
			if(textField_Id.getText()!= "")DAO_Cand.Read_ID(Cand,textField_Id.getText());
			AfficheCandidats();
			
			con.Connexion().close();

			Clean();
			
		}catch(Exception e) {
			Msg_Box.message_box(e,"Afficher Controller");
		}
	}
	
	public void OnClickClean(ActionEvent event) {
		try {
			Clean();
		} catch (Exception e) {
			// TODO: handle exception
			Msg_Box.message_box(e, "Contriller Clean");
		}
	}
}