package application;

import javafx.fxml.*;
import javafx.scene.control.*;

import java.net.URL;
import java.util.ResourceBundle;

import Classes.*;
import DAO_Pa.*;
import javafx.event.ActionEvent;

public class FormController implements Initializable {
	
	public Message_Box Msg_Box = new Message_Box();
	
	public DAO_Candidat DAO_Cand = new DAO_Candidat();;
	public Candidat Cand;
	public Connect con;
	
	@FXML
	private TextField textField_Id, textField_Nom, textField_Prenom, textField_MAil, textField_Adresse, textField_Ville, textField_Pays;
	
	@FXML
	private TableColumn<Candidat, String> Candid_Id, Candid_Nom, Candid_Pre, Candid_Mail, Candid_Adr, Candid_Ville, Candid_Pays;
	@FXML
	private TableView<Candidat> TableView_Aff; 
	



	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		try {

			Cand = new Candidat();
			
			DAO_Cand.Read(Cand);
			
			TableView_Aff = new TableView<Candidat>();
			
			
			// Create column UserName (Data type of String).
			Candid_Id = new TableColumn<Candidat, String>("Identifiant");

			// Create column Email (Data type of String).
			Candid_Nom = new TableColumn<Candidat, String>("Nom");

			// Create column FullName (Data type of String).
			Candid_Pre = new TableColumn<Candidat, String>("Prenom");
			
			// Create 2 sub column for FullName.
			Candid_Mail = new TableColumn<Candidat, String>("Mail");

			Candid_Adr = new TableColumn<Candidat, String>("Adresse");

			Candid_Ville = new TableColumn<Candidat, String>("Ville");

			Candid_Pays = new TableColumn<Candidat, String>("Pays");

			TableView_Aff.getColumns().addAll(Candid_Id, Candid_Nom, Candid_Pre, Candid_Mail, Candid_Adr, Candid_Ville, Candid_Pays);

			StackPane root = new StackPane();
			root.setPadding(new Insets(7));
			root.getChildren().add(TableView_Aff);

			Stage stage = new Stage();
			stage.setTitle("TableView (o7planning.org)");

			con.Connexion().close();
			
			
//			data.addAll(userDao.getAll());
//	        clmnid.setCellValueFactory(new PropertyValueFactory<User, Integer>("idUser"));
//	        clmnfrstnm.setCellValueFactory(new PropertyValueFactory<User, String>("firstname"));
//	        clmlstnm.setCellValueFactory(new PropertyValueFactory<User, String>("lastname"));
//	        clmnmail.setCellValueFactory(new PropertyValueFactory<User, String>("email"));
//	        clmnadress.setCellValueFactory(new PropertyValueFactory<User, String>("adresse"));
//	        clmncity.setCellValueFactory(new PropertyValueFactory<User, String>("city"));
//	        clmncntry.setCellValueFactory(new PropertyValueFactory<User, String>("country"));
//	        tableView.setItems(data);
			
		}catch(Exception e) {
			Msg_Box.message_box(e);
		}
		
	}
	
	
	@FXML
	public void OnClickAjouter(ActionEvent event) {
		// TODO Autogenerated
		try {
			Cand = new Candidat(textField_Id.getText(), textField_Nom.getText(), textField_Prenom.getText(), textField_MAil.getText(), textField_Adresse.getText()
					, textField_Ville.getText(), textField_Pays.getText());

			DAO_Cand.Create(Cand);
			
			con.Connexion().close();
			
			Msg_Box.Clean();
		}catch(Exception e) {
			Msg_Box.message_box(e);
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void OnClickModifier(ActionEvent event) {
		// TODO Autogenerated
		try {
			Cand = new Candidat(textField_Id.getText());
			
			DAO_Cand.Update(Cand);
			
			con.Connexion().close();

			Msg_Box.Clean();
			
		}catch(Exception e) {
			Msg_Box.message_box(e);
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void OnClickSupprimer(ActionEvent event) {
		// TODO Autogenerated
		try {
			Cand = new Candidat(textField_Id.getText());
			
			DAO_Cand.Delete(Cand);
			
			con.Connexion().close();
			
			Msg_Box.Clean();
			
		}catch(Exception e) {
			Msg_Box.message_box(e);
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void OnClickAfficher(ActionEvent event) {
		// TODO Autogenerated
		try {
			Cand = new Candidat();
			
			DAO_Cand.Read_ID(Cand,textField_Id.getText());
			
			con.Connexion().close();

			Msg_Box.Clean();
			
		}catch(Exception e) {
			Msg_Box.message_box(e);
		}
	}
}
