package application;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;

import java.text.MessageFormat;

import javafx.event.ActionEvent;

public class FormController {
	
	public static void message_box(Exception e) {
		Alert alert = new Alert(Alert.AlertType.INFORMATION);
		alert.setTitle("Message Here...");
	    alert.setHeaderText("Une Erreur");
	    alert.setContentText(e.getMessage());
	    alert.showAndWait();
	}

	
	// Event Listener on Button.onAction
	@FXML
	public void OnClickAjouter(ActionEvent event) {
		// TODO Autogenerated
		try {
			
			
			
		}catch(Exception e) {
			message_box(e);
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void OnClickModifier(ActionEvent event) {
		// TODO Autogenerated
		try {
			
		}catch(Exception e) {
			message_box(e);
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void OnClickSupprimer(ActionEvent event) {
		// TODO Autogenerated
		try {
			
		}catch(Exception e) {
			message_box(e);
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void OnClickAfficher(ActionEvent event) {
		// TODO Autogenerated
		try {
			
		}catch(Exception e) {
			message_box(e);
		}
	}
}
