package Controllers;

import javafx.fxml.*;
import javafx.scene.*;
import javafx.scene.control.*;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

import DAO_Pa.DAO_Candidat;
import Models.Candidat;
import Models.Connect;
import Models.Message_Box;
import javafx.application.Platform;
import javafx.event.ActionEvent;

public class LoginController{
	@FXML
	private TextField TextFild_FiNa, TextFild_LaNa;
	
	public Stage primaryStage;
	public Message_Box Msg = new Message_Box();

	public DAO_Candidat DAO_Cand = new DAO_Candidat();;
	public Candidat Cand;
	public Connect con = new Connect();
	
	public void Oppen_Form(String lien) {
		try {
			Scene scene = new Scene(FXMLLoader.load(getClass().getResource(lien)));
			
			primaryStage = new Stage();
			
			
			primaryStage.setScene(scene);
			
			primaryStage.show();
			
			//primaryStage.hide();
			//Platform.Hide();
			
			
		} catch(Exception e) {
			Msg.message_box(e, "Open Form");
		}
	}
	// Event Listener on Button.onAction
	
	@FXML
	public void OnClickConnected(ActionEvent event){
		// TODO Autogenerated
		try {
			Cand = new Candidat();

			DAO_Cand.test_Connection(Cand ,TextFild_FiNa.getText() ,TextFild_LaNa.getText());
			
			if(Cand.getNom() != null) Oppen_Form("/View/Form.fxml");
			else {
				TextFild_FiNa.setText("");
				TextFild_LaNa.setText("");
				
				TextFild_FiNa.setStyle("-fx-background-color: red;");
				TextFild_LaNa.setStyle("-fx-background-color: red;");
			}
				
			con.Connexion().close();
			
		} catch (Exception e) {
			// TODO: handle exception
			Msg.message_box(e, "Connect login");
		}
	}

	public void OnKeyPressedFiNam() {
		TextFild_FiNa.setStyle("-fx-background-color: White;");
	}
	
	public void OnKeyPressedLaNam() {
		TextFild_LaNa.setStyle("-fx-background-color: White;");
	}
	
	public void OnClickedSignIn(MouseEvent mouseEvent) {
		Oppen_Form("/View/Sign In.fxml");
	}

	
}
